### ISSUE TITLE
Does POM need to include all of aws-java-sdk?

### ISSUE THREAD

**Issue by paulhoadley** [meltmedia/jgroups-aws#13]
Dependency on `aws-java-sdk` pulls in almost 70 JARs. Could this be trimmed to a subset of those?

**Comment by ctrimble** [comment]
@paulhoadley the current dependency tree is based on the old `aws-java-sdk`, that came in one jar.  I would be happy to support a PR that moves the project up to a modern version of the SDK.

**Comment by paulhoadley** [comment]
I've created #14.
