### ISSUE TITLE
jgroups-aws doesnt support VPC/proxies

### ISSUE THREAD

**Issue by mfranklin1** [meltmedia/jgroups-aws#3]
Looking at the code it doesnt appear to support either other aws regions - see http://docs.aws.amazon.com/general/latest/gr/rande.html#ec2_region 

Nor the use of a proxy - needed to get access to amazon if you dont have direct aws access from your aws vpc.

I'll update the code locally to support this (done it a few times before for other reasons). Let me know if you'd like me to provide an update with the fixes in it.

**Comment by jebl01** [comment]
three years old... is this (still) an issue? Was thinking of having a go, but we are in eu-central-1...

**Comment by ctrimble** [comment]
@jeb01 as far as I know, all regions are be supported.  Nothing has been done for proxy support.

**Comment by kenwdelong** [comment]
I am running in us-west-2, no problem.

**Comment by jebl01** [comment]
👍

**Comment by ctrimble** [comment]
Closing this as invalid.
