### ISSUE TITLE
Review compatibility with JGroups 3.5.0.Beta7

### ISSUE THREAD

**Issue by ctrimble** [meltmedia/jgroups-aws#4]
Bela sent out an [email](http://sourceforge.net/p/javagroups/mailman/message/32389968/)  today about the release of version 3.5.0.Beta7.  We should evaluate this project relative to that coming release.

**Comment by Shabin** [comment]
Hi, what is the status of the evaluation for the latest version of jgroups(3.6.x)?. Are you planning for an upgrade? If not, can you please give me a solution for using latest jgroups in AWS.

**Comment by ctrimble** [comment]
@Shabin this ticket is stalled and we do not have a plan to do an update any time soon.  I would be happy to review any PRs related to this and get a version for 3.6 out on maven central.

**Comment by ctrimble** [comment]
Compatibility problems with JGroups 3.5.0+ were resolved in release 1.4.0.
