### ISSUE TITLE
Running Chat demo doesn't seem to work if you don't specify -Djava.net.preferIPv4Stack=true

### ISSUE THREAD

**Issue by grange74** [meltmedia/jgroups-aws#6]
The Readme has the following command:
mvn exec:java -Dexec.mainClass="org.jgroups.demos.Chat" -Dexec.args="-props conf/aws_ping.xml"

But when i ran it, the 2 EC2 instances running the Chat demo couldn't seem to talk to each other. After adding -Djava.net.preferIPv4Stack=true and running it again it work after a while.

So using the following command:
mvn exec:java -Dexec.mainClass="org.jgroups.demos.Chat" -Dexec.args="-props conf/aws_ping.xml" -Djava.net.preferIPv4Stack=true

I was getting the following warning sometimes which stopped the other EC2 instances message:
Jan 23, 2015 4:27:33 AM org.jgroups.logging.JDKLogImpl warn
WARNING: ip-172-31-11-65-19587: dropped message 12 from ip-172-31-0-254-8352 (sender not in table [ip-172-31-11-65-19587]), view=[ip-172-31-11-65-19587|0] [ip-172-31-11-65-19587]

**Comment by ctrimble** [comment]
Thanks for the info, I will take a look at this.

**Comment by ctrimble** [comment]
There is some information in the [documentation](http://www.jgroups.org/manual/html/ch02.html#IPv6Issues) about this issue.
